### ISSUE TITLE
Build failed with error code: 1

### ISSUE THREAD

**Issue by bereska** [ShahanaFarooqui/RTL#148]
**Describe the bug**
upgrading from 0.2.15 to 0.3.2 got this error

**To Reproduce**
cd RTL
sudo su
git reset --hard HEAD
git clean -f -d
git pull
npm install

RTL upgraded and is accessible via webpage
however install ended up with errors below
should i just ignore it?

**Expected behavior**
ok, no errors
**Actual behavior**
`Building: /usr/bin/node /home/admin/RTL/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/admin/RTL/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.15.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 11.15.0
gyp verb command install [ '11.15.0' ]
gyp verb install input version string "11.15.0"
gyp verb install installing version: 11.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/11.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/admin/RTL/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '11.15.0' ]
gyp verb install input version string "11.15.0"
gyp verb install installing version: 11.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 11.15.0
gyp verb ensuring nodedir is created /home/admin/RTL/node_modules/node-sass/.node-gyp/11.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '11.15.0' ]
gyp verb remove using node-gyp dir: /home/admin/RTL/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 11.15.0
gyp verb remove removing development files for version: 11.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '11.15.0' ]
gyp verb remove using node-gyp dir: /home/admin/RTL/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 11.15.0
gyp verb remove removing development files for version: 11.15.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/admin/RTL/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/home/admin/RTL/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/admin/RTL/node_modules/node-sass
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN angular-user-idle@2.0.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-user-idle@2.0.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-13T18_11_26_044Z-debug.log`

**Screenshots**

**Your environment**
Raspiblitz 1.1 on rpi 3b+
lnd 0.6.0
bitcoin 0.17.0

**Additional context**

**Comment by bereska** [comment]
and I forgot to say 'thank you' for the great tool)

**Comment by saubyk** [comment]
Hi @bereska 
This seems to be a problem in your install:
```
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/admin/RTL/node_modules/node-sass/.node-gyp'
```
Can you try running `npm install` with the root user and see if it runs without any issues?

**Comment by bereska** [comment]
hi @saubyk, thank you. I did run it under root
cd RTL
**sudo su**
git reset --hard HEAD
git clean -f -d
git pull
npm install

**Comment by bereska** [comment]
also getting this in logs:
admin@bereskaLND:~ $ sudo journalctl -u RTL -f
-- Logs begin at Tue 2019-05-14 16:32:55 BST. --
May 14 21:46:15 bereskaLND node[30679]: Error [ERR_CRYPTO_HASH_FINALIZED]: Digest already called
May 14 21:46:15 bereskaLND node[30679]:     at Hash.update (internal/crypto/hash.js:61:11)
May 14 21:46:15 bereskaLND node[30679]:     at /home/admin/RTL/controllers/authenticate.js:99:28
May 14 21:46:15 bereskaLND node[30679]:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
May 14 21:46:16 bereskaLND systemd[1]: RTL.service: Main process exited, code=exited, status=1/FAILURE
May 14 21:46:16 bereskaLND systemd[1]: RTL.service: Unit entered failed state.
May 14 21:46:16 bereskaLND systemd[1]: RTL.service: Failed with result 'exit-code'.
May 14 21:46:46 bereskaLND systemd[1]: RTL.service: Service hold-off time over, scheduling restart.
May 14 21:46:47 bereskaLND systemd[1]: Stopped RTL daemon.
May 14 21:46:47 bereskaLND systemd[1]: Started RTL daemon.

**Comment by ShahanaFarooqui** [comment]
Hi, it is an open issue at sass/node-sass github at https://github.com/sass/node-sass/issues/2652. They are asking for the full error log, can you please copy the content of your log file ‘/root/.npm/_logs/2019-05-13T18_11_26_044Z-debug.log` here or at node-sass’s github? Thanks.

**Comment by bereska** [comment]
hi @ShahanaFarooqui, thank you. here it is https://www.dropbox.com/s/etdeio90ca62s0r/2019-05-13T18_11_26_044Z-debug.log?dl=0

**Comment by ShahanaFarooqui** [comment]
@bereska, Till node-sass fixes the issue from their end, you can use RTL with attached downgraded dependencies. Please replace your RTL's package.json and package-lock.json with attached files and run npm install again.

[node-sass-temp-fix.zip](https://github.com/ShahanaFarooqui/RTL/files/3189574/node-sass-temp-fix.zip)

**Comment by bereska** [comment]
hi @ShahanaFarooqui, thank you. Unfortunately the .zip file id corrupt or incomplete. Please upload again. Than you

**Comment by ShahanaFarooqui** [comment]
@bereska Please follow below steps:
1) Delete your package-lock.json
2) Replace content from 'https://pastebin.com/h1e3EYm0' into your package.json. 
3) run 'npm install'. Successfull installation will create a new package-lock.json for you.

**Comment by pandeykumar** [comment]
Thanks . Noticed that .zip was corrupt. Tried with new package.json content with not package-lock.json and empty node_modules folder -   
Seeing similar issue  -
---------Log Details . ---

........
33115 silly saveTree └── zone.js@0.8.29
33116 warn codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
33117 warn codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
33118 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
33119 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
33120 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
33120 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
33120 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
33120 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
33121 verbose stack Error: node-sass@4.12.0 postinstall: `node scripts/build.js`
33121 verbose stack Exit status 1
33121 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
33121 verbose stack     at EventEmitter.emit (events.js:193:13)
33121 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
33121 verbose stack     at ChildProcess.emit (events.js:193:13)
33121 verbose stack     at maybeClose (internal/child_process.js:999:16)
33121 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
33122 verbose pkgid node-sass@4.12.0
33123 verbose cwd /home/admin/RTL
33124 verbose Linux 4.14.98-v7+
33125 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
33126 verbose node v11.15.0
33127 verbose npm  v6.5.0
33128 error code ELIFECYCLE
33129 error errno 1
33130 error node-sass@4.12.0 postinstall: `node scripts/build.js`
33130 error Exit status 1
33131 error Failed at the node-sass@4.12.0 postinstall script.
33131 error This is probably not a problem with npm. There is likely additional logging output above.
33132 verbose exit [ 1, true ]

**Comment by ShahanaFarooqui** [comment]
Appologies for the confusion, I pasted the incorrect version ;).
package.json=> https://pastebin.com/DAKf8izR
package-lock.json=> https://pastebin.com/0wj2KX35

Either 
    Replace both package.json and package-lock.json from above pastebin location. 
    Run 'npm install'
OR 
    Replace packge.json, 
    Delete package-lock
    Run 'npm install'

**Comment by bereska** [comment]
thank you, @ShahanaFarooqui. I followed the steps above but it still gives me the same error. However it createsa new package-lock.json

**Comment by bereska** [comment]
in general RTL 0.3.3 is now running but it is just super slow in webGUI

**Comment by pandeykumar** [comment]
Good news , I removed nodejs  and npm install .
Deleted the RTL folder and ran 
``` sudo /home/admin/config.scripts/bonus.rtl.sh ```
That seems to have done the trick.  RTL is up and running !!
Thanks

**Comment by bereska** [comment]
hi @pandeykumar, thank you. Please specify what your environment is what exactly you did.

**Comment by pandeykumar** [comment]
######
Env  on raspi 
#######             
RaspiBlitz v1.2  kcryptlnd
               bitcoin Fullnode + Lightning Network 
        ,/     -------------------------------------------
      ,'/      CPU load 0.64, 0.64, 0.67, temp 59°C 91°F
    ,' /       Free Mem 502M / 927M  Free HDD 587G (64%)
  ,'  /_____,  ssh admin@192.168.1.5 ▼0.0B ▲0.0B
 .'____    ,'  web admin --> http://192.168.1.5:3000
      /  ,'    bitcoin v0.17.1 mainnet Sync OK 100.00%
     / ,'      Public 24.6.231.246:8333 8 connections
    /,'        
   /'          LND 0.6.0-beta wallet 835481 sat 
               0/0 Channels 0 sat 3 peers
RTL : latest from github 
~/RTL $ git status
On branch master

The cleanup and re-install 
1.   Remove the current nodejs and npm insall ```sudo apt-get remove nodejs```
2.  Remove current RTL directory under /home/admin/RTL .  ``` rm -rf /home/admin/RTL ```
3.  Run the /home/admin/config.scripts/bonus.rtl.sh  ```./home/admin/config.scripts/bonus.rtl.sh```

I had bitcoind and lnd already running.

**Comment by bereska** [comment]
@pandeykumar, thank you. I have a similar setup of raspiblitz 1.1 with Bitcoin 0.18, lnd 0.6.1 + btcpayserver on top. Did you end up with RTL 0.3.3 after this update?

**Comment by ShahanaFarooqui** [comment]
Hi @bereska, It looks like @pandeykumar's problem was related to npm cache, which was solved by uninstalling the node. Below steps might be helpful in that case:

Remove RTL/node_modules
Remove RTL/package-lock.json
Go to command and run 'npm cache clear', 'npm cache verify' and 'npm install' sequencially in RTL root.

Regarding slower GUI: RTL v3 doesn't have any reason to be slower than v2. Please check other environmental factors for that, ie RAM, CPU etc.

**Comment by pandeykumar** [comment]
My bad , did not realize this section in config.scripts/bonus.rtl.sh   that I was using to install RTL.
So I was running 0.2.16.   Will get the latest and try again and see how that goes ..
```
    git clone https://github.com/ShahanaFarooqui/RTL.git
    cd RTL
    git reset --hard v0.2.16
```

**Comment by bereska** [comment]
@ShahanaFarooqui, thank you. I tried your solution but it still exited with the same error code. I also agree with you that it is slow because I have bitcoind, lnd, rtl, btcpayserver+nbxplorer all running on rpi 3b+. It's just too much for the little pi. However I want to continue this experiment and optimize the processes to let pi pull it off since it's the least expensive self-hosted setup so far. 
@pandeykumar, thank you. Then I tried your solution changing the script to 'git reset --hard HEAD' to get the latest version of RTL. But when I ran ./bonus.rtl.sh it just printed this:
"small config script to switch WebGUI RideTheLightning on or off"
 "bonus.rtl.sh [on|off]"
So I disabled RTL service in RaspiblitzGUI and reboot the system. Then enabled RTL and it gave me the same very error: Build failed with error code: 1
However the RTL GUI is available
Should i just ignore this error for now?

**Comment by ShahanaFarooqui** [comment]
Hi @bereska, after exhausting almost all possible options, it looks like Ignoring is the only option we are left with ;). So let us do that for now. Hopefully, node-sass will fix the issue at their end soon.

**Comment by bereska** [comment]
Hi @ShahanaFarooqui, thank you for your help and the excellent tool to explore the lightning net work)

**Comment by ShahanaFarooqui** [comment]
@bereska 
node-sass team suggested to use --unsafe-perm option while intalling npm dependencies as node-sass requires some scripts to run after its installation. 

Running the unsafe-perm is not always recommended but when running npm install as admin, npm disables the scripts to run autoatically. Which is the main reason of failure in your case.

Replacing the node-sass library in the application, at this point, is not an option. We would suggest that while running the node-sass script is not harmful, you should decide yourself if you want to install RTL with unafe-perm option or not. 

Some references: 
https://stackoverflow.com/questions/49294107/installing-npm-node-sass
https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/
https://docs.npmjs.com/misc/config

**Comment by bereska** [comment]
@ShahanaFarooqui, thank you. Just upgraded to 0.4.3-bets with --unsafe-perm flag. It worked!
thank for your attention to this minor issue

**Comment by ShahanaFarooqui** [comment]
@bereska, no issue is minor issue till it is resolved :). Thanks for using RTL, closing the issue now.

**Comment by goodc0re** [comment]
In order to resolve this login / authentication issue: https://github.com/ShahanaFarooqui/RTL/issues/143 I tried multiple times to update RTL, both manually as well as via the raspiblitz menu, but also observed the same issue, build error. 

I tried to update manually with npm install --unsafe-perm and it looked like it worked, but it did not resolve the login / authentication problem.

**Comment by ShahanaFarooqui** [comment]
@goodc0re, we will need more details in order to understand the issue. Please share details from your conf file and other environment and versions details. Thanks.
